[package]
name = "tpx"
version = "0.1.0"
description = "Task scheduler"
edition = "2021"
homepage = "https://github.com/mira-merkell/tpx"
license = "MIT"
readme = "README.md"
repository = "https://github.com/mira-merkell/tpx.git"

[dependencies]
rayon = "1.7.0"
